# Generated by Django manual schema converter
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('pengarang', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=255)),
                ('tahun_terbit', models.IntegerField(blank=True, null=True)),
                ('rak', models.CharField(max_length=50)),
                ('stok', models.IntegerField(default=1, blank=True, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'buku',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('kelas', models.CharField(max_length=50)),
                ('nis', models.CharField(max_length=50, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'siswa',
            },
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_pinjam', models.DateField(default=django.utils.timezone.now, blank=True, null=True)),
                ('jatuh_tempo', models.DateField()),
                ('keperluan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Dipinjam', max_length=50, blank=True, null=True)),
                ('petugas', models.CharField(max_length=100, blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, db_column='buku_id', to='perpustakaan.buku', blank=True, null=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, db_column='siswa_id', to='perpustakaan.siswa', blank=True, null=True)),
            ],
            options={
                'db_table': 'peminjaman',
            },
        ),
    ]